name: Sappie Bot

on:
  schedule:
    # Sacred times in UTC (UK time - 1 hour in winter, - 0 hours in summer)
    - cron: '9 0 * * *'  # 12:09 AM UK
    - cron: '11 1 * * *' # 1:11 AM UK
    - cron: '22 2 * * *' # 2:22 AM UK
    - cron: '33 3 * * *' # 3:33 AM UK
    - cron: '44 4 * * *' # 4:44 AM UK
    - cron: '55 5 * * *' # 5:55 AM UK
    - cron: '39 6 * * *' # 6:39 AM UK (Tesla's 369)
    - cron: '11 11 * * *' # 11:11 AM UK
    - cron: '22 12 * * *' # 12:22 PM UK
    - cron: '33 13 * * *' # 1:33 PM UK
    - cron: '44 14 * * *' # 2:44 PM UK
    - cron: '55 15 * * *' # 3:55 PM UK
    - cron: '11 16 * * *' # 4:11 PM UK
    - cron: '22 17 * * *' # 5:22 PM UK
    - cron: '33 18 * * *' # 6:33 PM UK
    - cron: '44 19 * * *' # 7:44 PM UK
    - cron: '55 20 * * *' # 8:55 PM UK
    - cron: '10 22 * * *' # 10:10 PM UK
  workflow_dispatch: # Allow manual triggering

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        AITABLE_TOKEN: ${{ secrets.AITABLE_TOKEN }}
        AITABLE_DATASHEET_ID: ${{ secrets.AITABLE_DATASHEET_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: node sappie_bot.js 